// Configuration constants
module.exports = {

  MAX_RETRIES: 3, 

 
  RATE_LIMIT_MAX_REQUESTS: 10, 
  RATE_LIMIT_INTERVAL_MS: 60 * 1000, 

 
  QUEUE_PROCESS_INTERVAL_MS: 5 * 1000, 
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: 5,
  CIRCUIT_BREAKER_RESET_TIMEOUT_MS: 30 * 1000, 

  
  PROVIDER_A_FAILURE_RATE: 0.3, 
  PROVIDER_B_FAILURE_RATE: 0.4, 
};